default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: postgres_infratop

development:
  <<: *default
  database: develop_postgresql

test:
  <<: *default
  database: test_postgresql

production:
  <<: *default